"use client";

export default function Leftsolar4on() {
  return (
    <div>
      <h2 className=" text-lg md:text-3xl font-bold text-cyan-700  my-2 mb-6">
        Net metering on on-grid solar system
      </h2>
      <p className="text-orange-500 md:text-lg text-sm mb-4 leading-relaxed">
        The entire concept of an on-grid solar system works on the principle of
        net metering.
        <br />
        <br />
        Net metering can be best understood as a means for the discom to keep a
        track of the power that was generated by the solar plant, the power that
        was consumed, the power that was supplied to the grid, and the power
        that was imported.
        <br />
        <br />
        At the end of every month when the electricity bill is generated, the
        readings from the bidirectional meter give an account of:
      </p>
      <ul className="list-disc pl-4 marker:text-3xl my-auto marker:text-cyan-700 mb-6 md:text-lg text-sm">
        <li className="text-orange-500">
          <p>1. How many units were supplied to the grid</p>
        </li>
        <li className="text-orange-500">
          <p>2. How many units were taken from the grid</p>
        </li>
        {/* <li className="text-orange-500">
          <p>Mounting structures</p>
        </li>
        <li className="text-orange-500">
          <p>Bi-directional meter</p>
        </li>
        <li className="text-orange-500">
          <p>Solar accessories</p>
        </li> */}
        {/* <li className="text-orange-500">
          <p>Solar accessories</p>
        </li> */}
      </ul>
      <p className="text-orange-500 md:text-lg text-sm mb-4 leading-relaxed">
        If you supplied more than you consumed, those units will be deducted
        from your bill. It will reduce the bill further.
        <br />
        <br />
        If you had to use extra units from the grid on top of what your solar
        plant generated, those units would be added to your bill.
      </p>
      <h2 className=" text-lg md:text-3xl font-bold text-cyan-700  my-2 mb-6">
        Top 8 benefits of using an on-grid solar system
      </h2>
      <p className="text-orange-500 md:text-lg text-sm mb-4 leading-relaxed">
        A solar system is of 3 types: on-grid, off-grid, and hybrid
        <br />
        <br />
        Although there are three types, it’s the on-grid solar system that’s
        used and trusted by most homeowners in India.
        <br />
        <br />
        Naturally, there ought to be some extraordinary benefits of an on-grid
        solar system for home.
        <br />
        <br />
        Those are the benefits we’re focusing on:
      </p>
      <ul className="list-disc pl-4 marker:text-3xl my-auto marker:text-cyan-700 mb-6 md:text-lg text-sm">
        <li className="text-orange-500">
          It’s easy to keep a track of the units of electricity that your solar
          system generated
        </li>
        <li className="text-orange-500">
          It’s easier to understand the solar electricity bill
        </li>
        <li className="text-orange-500">
          Once the solar on-grid system’s price breaks even in 3 to 5 years, you
          get free solar electricity for the next 20-22 years
        </li>
        <li className="text-orange-500">
          The monthly electricity bill reduces substantially
        </li>
        <li className="text-orange-500">
          There’s no battery requirement. Your grid plays the role of the
          battery. The system will directly supply excess units to the grid and
          take them back when needed
        </li>
        <li className="text-orange-500">
          Since there’s no battery, there are no battery replacement charges
          involved
        </li>
        <li className="text-orange-500">
          Out of all the 3 types of solar systems, the on-grid solar system for
          homes is the most affordable option
        </li>
        <li className="text-orange-500">
          The government offers a subsidy only on an on-grid solar system for
          residential homes (that use DCR panels)
        </li>
      </ul>
      <h2 className=" text-lg md:text-3xl font-bold text-cyan-700  my-2 mb-6">
        Power outages on on-grid solar systems
      </h2>
      <p className="text-orange-500 md:text-lg text-sm mb-4 leading-relaxed">
        Every system has benefits as well as certain limitations - an on-grid
        solar system is no different.
        <br />
        <br />
        Although its connection with the grid is a sure benefit, it's also a
        limitation. When there's a power cut from the grid, the on-grid solar
        system automatically shuts down.
        <br />
        <br />
        This interruption in the supply of power is known as a power outage.
        Nevertheless, on-grid solar systems in urban areas with a reliable grid
        are unbeatable when it comes to meeting all the power requirements of a
        home.
        <br />
        <br />
        The main reason that an on-grid solar inverter is designed in a way that
        it automatically shuts down if the grid fails is to eliminate safety
        risks. This particular feature that differentiates on-grid inverters
        from all other types is called Anti-Islanding Protection.
        <br />
        <br />
        During power outages, an on-grid inverter will stop generating AC power
        immediately. Otherwise, the electrical maintenance personnel working
        directly with the wiring at the location of the electrical fault may
        suffer from electric shocks.
      </p>

      <h2 className=" text-lg md:text-3xl font-bold text-cyan-700  my-2 mb-6">
        On-grid Solar system types based on their capacities
      </h2>
      <p className="text-orange-500 md:text-lg text-sm mb-4 leading-relaxed">
        In terms of subsidy, the government offers a subsidy for an on-grid
        solar system that uses DCR panels. For those consuming 0-150 units per
        month, a subsidy ranging from ₹30,000 to ₹60,000 is available for 1-2 kW
        solar plants. Households with a consumption of 150-300 units can receive
        between ₹60,000 and ₹78,000 for 2-3 kW systems, while those consuming
        over 300 units are eligible for ₹78,000 for systems above 3 kW.
        <br />
        <br />
        Let’s find out the basics since the calculations will also help you in
        finding out the size of the solar system that you should install at your
        home.
       
      </p>
       <h4 className=" text-lg md:text-2xl font-bold text-cyan-700  my-1 mb-3">1 kW on-grid solar system</h4>
        <p className="text-orange-500 md:text-lg text-sm mb-4 leading-relaxed">A 1 kW grid-tied solar system produces roughly 1400 units of electricity on an average/year, which means:</p>
        <ul className="list-disc pl-4 marker:text-3xl my-auto marker:text-cyan-700 mb-6 md:text-lg text-sm">
          <li className="text-orange-500">The approximate units generated by a 1 kW on-grid solar system in a month will be 116 units (1400/12)</li>
          <li className="text-orange-500">If the average electricity tariff/unit in your city is ₹8, you will save approximately ₹11,200 in one year (1400 X 8)</li>
        </ul>
    </div>
  );
}
